---
title: "Datatransformatie: van XML naar JSON"
description: |
  Een beschrijving van de volledige workflow in Node.js
author:
  - name: Witek ten Hove
    url: https://www.linkedin.com/in/witektenhove/
date: 10-01-2018
output:
  radix::radix_article:
    self_contained: false
---

### De casus

Een organisatie is voor een online dienst afhankelijk van overheidsdata. De data heeft een asymmetrische structuur en wordt daarom als een XML-bestand aangeboden. Uiteindelijk zal de data worden verwerkt op de website en doorzoekbaar zijn. In een eerste tussenstap dient de data te worden vertaald naar een JSON-formaat.

### Asymmetrische data
De bekendste manier om data op te slaan, is door gebruik te maken van tabellen. Een data-element wordt dan in een cel bewaard en alle cellen vormen rijen en kolommen:


| Voor         | Tussen      | Achter       |
| ------------ |------------ | ------------ |
| Witold       | ten         | Hove         |
| Caroline     |             | Tensen       |

Dit is een vorm van symmetrische data: iedere rij bevat evenveel velden en in ieder veld staat maar één data-element.

Soms echter kan het nodig zijn om in één veld meerdere data-elementen op te slaan. Stel bijvoorbeeld dat alle voornamen van een persoon moeten worden bewaard Sommige mensen hebben maar één voornaam en anderen meerdere. Een keuze kan zijn om in één cel meerdere namen te plaatsen:

| Voor                   | Tussen      | Achter       |
| ---------------------- |------------ | ------------ |
| Witold frederik        | ten         | Hove         |
| Caroline               |             | Tensen       |

Dit zal echter een probleem veroorzaken bij het filteren of sorteren van data. Ook wordt het moeilijk om een data-element te selecteren en het aan te passen of te verwijderen. Een standaard SQL-database beschouwt de waarden in een cel als één geheel.


### Wat is XML?
Het bovengenoemde probleem kan worden opgelost door data asymmetrisch op te slaan in zogenaamde `key: value` structuren. XML (**Extensible Markup Language**) is hier een voorbeeld van.

XML is een taal waarmee tekstbestanden kunnen worden voorzien van annotaties. Met deze zogenaamde *tags* kan data aan onderdelen van het tekstbestand worden toegevoegd die betekenis geven aan de geselecteerde tekst. Bijvoorbeeld kan een stuk tekst als woonplaats worden gekenmerkt:

```
  <woonplaats>Leiden</woonplaats>
```
Een tekst die op deze wijze is geannoteerd, kan later makkelijker worden ontleed. Stel bijvoorbeeld dat voor een toepassing alle woonplaatsen van klanten nodig zijn. Via een query kan in dat geval op de tag `<woonplaats>` worden gefilterd.

Een tabel met naamgegevens zou als volgt kunnen worden ingericht:

```
<personen>
  <persoon id=1>
     <voor>Witold</voor>
     <voor>frederik</voor>
     <tussen>ten</tussen>
     <achter>Hove</achter>
  </persoon>
  <persoon id=2>
     <voor>Caroline</voor>
     <achter>Tensen</achter>
  </persoon>
</personen>
```
Op deze wijze is het eenvoudig om items aan te passen. Nu kan bijvoorbeeld de opdracht worden geven om de tweede voornaam van de persoon met id=1 te veranderen naar 'Frederik' of kan aan de persoon met id=2 een tweede voornaam worden toegevoegd:

```
  <persoon id=2>
     <voor>Caroline</voor>
     <voor>Egbertine</voor>
     <achter>Tensen</achter>
  </persoon>
```

